# build environment
FROM node:16-alpine

WORKDIR /app

RUN npm install -g json-server

COPY ./src/services/server.json ./

EXPOSE 3333

CMD ["json-server","server.json", "--port", "3333", "--delay", "700", "--host", "0.0.0.0"]
